- name: Copy mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongodb client
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present

- name: get the catalogue entires count
  ansible.builtin.command:  mongo --host {{MONGODB_HOST}} --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: entires_count
  when: component == "catalogue"

- name: get the user entires count
  ansible.builtin.command:  mongo --host {{MONGODB_HOST}} --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: entires_count
  when: component == "user"

- name: load catalogue data
  ansible.builtin.command: "mongo --host {{MONGODB_HOST}} < /app/schema/{{component}}.js"
  when: entires_count.stdout == "0" and component == "catalogue" # keep double quotes
  ignore_error: true

- name: load user data
  ansible.builtin.command: "mongo --host {{MONGODB_HOST}} < /app/schema/{{component}}.js"
  when: entires_count.stdout == "0" and component == "user" # keep double quotes
  ignore_error: true

